### ISSUE TITLE
Create read more slide

### ISSUE THREAD

**Issue by seran-shan** [WebstepTrondheim/domstol_landingpage#133]
# Feature
Create the read more slide. This slide should come after the way forward slide.

## Solution
The solution should be like this:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/73961180/210021247-0f366341-9139-43e5-9860-bb5ba6b1b92f.png">
Mobile version can be found on Figma

- [ ] Desktop
- [ ] Mobile

**Comment by schjoth** [comment]
Related to #126

**Comment by schjoth** [comment]
Remember to make it reusable for the Domstol case as well
